http:
  port: "8085"

thespacedevs:
  host: "lldev.thespacedevs.com"
  basepath: "/"
  protocol: "HTTP"
  
validation:
  status:
    regex: "^(Success|Failure|Partial Failure)$"
    message: "You have entered an incorrect launch status. Possible status options: Success, Failure, Partial Failure."
  launch_year:
    regex: "^([0-9]{4})$"
    message: "You have entered an incorrect launch year. The launch year should be in the YYYY format, for example, 1987."